#!/usr/bin/env bash
# Launch DbManagementTool — generated by setup/install.py
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
exec "$ROOT/../../../../../../usr/bin/python3" conDbUi.py "$@"
