@echo off
REM Launch DbManagementTool GUI - generated by setup/install.py
setlocal enableextensions
set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
set "VENV_PY=%ROOT%\..\..\..\..\..\..\usr\bin\python3"
if not exist "%VENV_PY%" (
    echo [FAIL] %VENV_PY% not found.
    echo Run install.bat to create the virtual environment first.
    pause
    exit /b 1
)
cd /d "%ROOT%"
"%VENV_PY%" "%ROOT%\conDbUi.py" %*
set "RC=%ERRORLEVEL%"
if not "%RC%"=="0" (
    echo.
    echo ERROR: DbManagementTool exited with code %RC%.
    pause
)
exit /b %RC%
