@echo off
REM DbManagementTool CLI - generated by setup/install.py
setlocal enableextensions
set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
set "VENV_PY=%ROOT%\..\..\..\..\..\..\usr\bin\python3"
cd /d "%ROOT%"
"%VENV_PY%" "%ROOT%\dbtool.py" %*
exit /b %ERRORLEVEL%
