@echo off
REM Start REST API server - generated by setup/install.py
setlocal enableextensions
set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
set "VENV_PY=%ROOT%\..\..\..\..\..\..\usr\bin\python3"
cd /d "%ROOT%"
echo Starting REST API on http://127.0.0.1:8000
echo Docs: http://127.0.0.1:8000/docs
"%VENV_PY%" "%ROOT%\dbtool.py" api --host 127.0.0.1 --port 8000
exit /b %ERRORLEVEL%
